services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/P@ssw0rd

      # --- Bolt 커넥터/TLS ---
      - NEO4J_server_bolt_enabled=true
      - NEO4J_server_bolt_tls__level=OPTIONAL          # 로컬 bolt:// + 외부 bolt+s:// 둘 다 허용

      # --- Bolt SSL 정책(인증서 경로/파일명 명시) ---
      - NEO4J_dbms_ssl_policy_bolt_enabled=true
      - NEO4J_dbms_ssl_policy_bolt_base__directory=/var/lib/neo4j/certificates/bolt
      - NEO4J_dbms_ssl_policy_bolt_public__certificate=public.crt   # fullchain.pem 복사본
      - NEO4J_dbms_ssl_policy_bolt_private__key=private.key         # privkey.pem  복사본
      - NEO4J_dbms_ssl_policy_bolt_client__auth=NONE

      # --- 리슨/광고 주소 ---
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_server_bolt_advertised__address=api.solyd.serve.cx:7687

    volumes:
      - neo4j_data:/data
      # 인증서 디렉터리(쓰기 가능; 엔트리포인트가 chown 시도함)
      - /opt/neo4j-certs/bolt:/var/lib/neo4j/certificates/bolt

  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  neo4j_data:
  postgres_data:
