[project]
name = "solyd-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.67.0",
    "fastapi[all]>=0.116.1",
    "neo4j>=5.28.2",
]
